;Music defines
def MUS_CNT				equ $0E

def MUS_END_GAME		equ $00
def MUS_RACE_WIN		equ $01
def MUS_RACE_LOSE		equ $02
def MUS_GAME_OVER		equ $03
def MUS_NEW_JUNK_CITY	equ $04
def MUS_SNOT_A_PROBLEM	equ $05
def MUS_FOR_PETES_SAKE	equ $06
def MUS_BUTTVILLE2		equ $07
def MUS_BUTTVILLE1		equ $08
def MUS_LEVEL5			equ $09
def MUS_ANDY_ASTEROIDS	equ $0A
def MUS_LIGHTS_OUT		equ $0B
def MUS_WHAT_THE_HECK	equ $0C
def MUS_DO_NOT_USE		equ $0D

;SFX defines
def SFX_CNT				equ $1A